import * as S from "@/styles/pages/Home";
import Head from "next/head";
import { Header } from "@/components/global/Header";
import { Partners } from "@/components/pages/home/Partners";
import { Form } from "@/components/pages/home/Form";
import { HeroSection } from "@/components/pages/home/HeroSection";
import { ServiceSection } from "@/components/pages/home/ServiceSection";
import { Footer } from "@/components/global/Footer";
import { News } from "@/components/pages/home/News";
import { FeatureSection } from "@/components/pages/home/FeatureSection";
import { CookieConsent } from "@/components/shared/cookieConsent";
import { Testimonial } from "@/components/pages/home/Testimonial";

export default function Home() {
  return (
    <S.Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <S.Main>
        <HeroSection />
        <FeatureSection />
        <Partners />
        <ServiceSection />
        <Form />
        <Testimonial />
        <News />
      </S.Main>
      <Footer />
      <CookieConsent />
    </S.Container>
  );
}
